source 'https://github.com/cocoapods/Specs.git'

inhibit_all_warnings!
use_frameworks!


def appPods
    pod "ViperMcFlurry", :path => "../ViperMcFlurry.podspec"
    pod "Typhoon", :git => 'git@github.com:RomanTruba/Typhoon.git', :branch => 'mac-storyboard-support'
end

target 'ViperMcFlurry_Example' do
    platform :ios, '8.0'
    appPods
end

target 'ViperMcFlurry_Tests' do
    platform :ios, '8.0'
    appPods
end

target 'OsxExample' do
    platform :osx, '10.8'
    appPods
end
